# Introduction

Nitrite and nitrate are two forms of nitrogen that can be found in freshwater systems and are indicators of nutrient pollution. The Delaware River is an important source of drinking water for millions of people, is an area for recreation, and provides a habitat for a variety of aquatic species. However, increasing levels of nitrate and nitrite concentrations in the river have raised concerns about the possible negative impacts the excessive levels can have on the water quality. In some locations within the Delaware River, nitrate and nitrite levels have exceeded the U.S. Environmental Protection Agency's recommendations.  (Delaware River Basin Commission, 2017). However, wetlands along the Delaware River could play a key role in removing nitrates and nitrites from the water.

Wetlands have been shown to have the ability to remove soluble nitrogen from the water in ways that are difficult to reproduce through man-made materials. Wetlands can remove nitrates and nitrites from the water through the denitrification process. Denitrification is the microbial removal of nitrates and nitrites into nitrogen and nitrous oxide (Skiba, 2008). Wetlands are rich in microbial diversity and the wetlands along the Delaware River provide a habitat for these microbial species involved in denitrification (Seo et al., 2015). Furthermore, plants that grow within the wetlands can uptake nitrate and nitrite to use for their growth in development. The presence of these plants helps with decreasing the concentration of the two nutrients (Nilsson et al., 2020). But the removal of nitrates and nitrites is also influenced by environmental factors such as temperature, pH, and dissolved oxygen concentrations in the water. 
Temperature conditions of the water can either increase or decrease the denitrification process thus resulting in higher or lower concentrations of nitrates and nitrites. Furthermore, higher temperatures have been shown to increase the rate of production for nitrates and nitrites resulting in higher concentrations during the summer months. Furthermore, in these months with higher temperatures, the solubility of gases leads to higher concentrations of nitrate and nitrite. Higher temperatures have also been associated with an increase in the nitrification process. The nitrification process involves bacteria converting ammonia into nitrite and then into nitrite (Liu et al., 2014). Therefore, an increase in this process would also lead to an increase in nitrate and nitrite concentrations. 

pH can also have an impact on nitrate and nitrite concentrations in water. Highly acidic conditions can lead to an increase in nitrate and nitrite concentrations while basic conditions tend to decrease these concentrations. However, some studies have shown that nitrate reduction may be more susceptible to change based on the pH conditions (Woltemade & Woodward, 2008). It can be noted though that pH only seems to have a very small influence on nitrate and nitrite removal through wetlands. 

Lastly, dissolved oxygen can play a key role in the nitrate and nitrite concentrations of water. Dissolved oxygen concentrations that are too low would lead to anoxic conditions. These low dissolved oxygen conditions allow for the denitrification process to occur which in turn would decrease the concentration of nitrate and nitrites in the water (Li et al., 2014). Soils found in wetlands are typically full of carbon and are anoxic. This provides the conditions necessary to remove nitrate and nitrite from the water (Cheng et al., 2020). Therefore, it is necessary to investigate dissolved oxygen levels to see how the nitrogen cycle happens in wetlands. Furthermore, it can show if the wetlands are active in the nutrient removal process or if it is a result of dissolved oxygen. 



