# Discussion 

## Wetland Removal

There was a statistically significant change in nitrate concentrations as water moved through the wetland locations. The findings indicate that the wetland area can effectively reduce the amount of nitrate in the water passing through it, which is a significant finding given the negative impacts that nitrate pollution can have on aquatic ecosystems. Additionally, the lack of a statistically significant difference in nitrate concentrations between the "in" and "after" positions suggests that most of the nitrate removal occurs early on in the wetland rather than towards the end. Furthermore, the relatively similar values of nitrate concentration throughout all seasons could be attributed to the industrial area surrounding the wetlands. This area could be providing a steady input of nitrate into the water leading to lower variability in the data set. The percent change in nitrate concentrations from the after position to the before being consistently positive also helps to show that nitrate concentrations are higher before passing through wetlands. Furthermore, the percent change from before to in was consistently negative but the percent change from in to after was both positive and negative. This helps to further signify that nitrate removal occurs within the earlier parts of the wetlands. It could also show that there are other possible nitrate inputs that occur near the end of the wetland. This would cause the after positions to have higher nitrate values than them in positions. However, the fact that the nitrate concentrations are still lower in the after position than in the before shows that despite these potential inputs, the wetlands are still able to filter excess nutrients out of the water thus leading to cleaner waterways. 

The results of the study showed that nitrite concentrations did not exhibit a significant change based on the location with respect to the wetlands in the Delaware River. The percent change graph also helped to show that there was no significant change for nitrite as it was highly variable with no clear pattern being recognized. With the percent change graph, the highest and lowest percent changes occurred in the same season at different water years and in the same position. This further shows that the wetlands did not have an impact on the nitrite concentrations in the water. However, unlike nitrate, it was observed that nitrite concentrations were usually higher in the fall season. This would show that in the fall excess nitrites are being added to the water during this time. It is also consistent with previous studies that have shown that nitrite levels tend to increase in the fall due to decreased sunlight and reduced biological activity. More research would have to be done to see if there is a certain outside factor that is causing variable nitrite levels throughout the wetlands.

## Environmental Factors

 There are other environmental impacts that could have impacted this data set. If this wetland is very high in organic material, it would make sense that the dissolved oxygen concentrations would be lower within and after the wetlands. The high amount of organic matter could lead to an increase in microbial activities that may deplete the oxygen supply. There was variability in temperature based on position, however, the data was not collected on the same day for each site. Because of this, it cannot be confirmed that wetlands have an impact on the temperature of water in this study. 
The average pH varied throughout the year and by location, however, the average pH for the Delaware River for all the water years was 7.3. This means that the water is usually not too acidic or basic. However, the pH of the water is more likely to become basic rather than acidic as the highest recorded value was 9.12 but the lowest was 6.3. The higher pH levels occurring in the summer months could be attributed to the increase in photosynthetic activity among the plants in the wetlands (Lowe et al., 2019). An increase in biological activity would lead to a decrease in pH which most likely occurs during the day in the summer. 

## Correlations

   Overall, there was very little correlation occurring between the different parameters studied. The strongest correlation coefficient was -0.92 between dissolved oxygen and temperature meaning that the two parameters may have an impact on one another. As temperature increases in the summer months dissolved oxygen would decrease and as temperature decreases in the winter, dissolved oxygen would increase. This coincides with previous research that has shown that as temperature increases, the solubility of oxygen decreases. This makes it harder for warmer waters to maintain dissolved oxygen concentrations. The second strongest correlation was between nitrite and dissolved oxygen. While the correlation coefficient was only -0.42 and therefore only considered to be of moderate correlation, some information can still be extracted. It could be possible that the amount of dissolved oxygen in the Delaware River could play a role in the concentration of nitrite. 
   However, due to the small correlation coefficients found for the rest of the data, it cannot be confirmed that dissolved oxygen, temperature, and pH play a role in the nitrate/nitrite concentrations that occur within wetlands. Therefore, it is more likely that the wetlands are the main source of nitrate/nitrite removal. However, there are other factors that could be considered such as vegetation and sediments in the water that were not studied. Further research could help to show if other environmental factors have a higher correlation to nitrate and nitrite concentrations. 
